FROM ppc64le/docker:17.12.0-dind
MAINTAINER David Wilder <wilder@ibm.com>

# Install iptables, ip6tables, iproute2, and perform glibc install as per:
RUN apk add --update iptables ip6tables ipset iproute2 curl busybox-extras && \
  echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
  rm -rf /var/cache/apk/*

